"""
task_template.py - Centralized metadata file templates

All watchers use the same base template with different field values.
This ensures consistency across all task types (file_drop, email, whatsapp, etc.)

Usage:
    from utils.task_template import create_file_drop_metadata, create_email_metadata
    
    # For Filesystem Watcher
    metadata = create_file_drop_metadata(
        original_name="invoice.pdf",
        original_path=Path("vault/Inbox/Drop/invoice.pdf"),
        content="File content...",
        file_hash="abc123...",
        size=1024,
        priority="high",
        timestamp=datetime.now()
    )
    
    # For Gmail Watcher (future)
    metadata = create_email_metadata(
        from_address="client@example.com",
        subject="Invoice #123",
        content="Email body...",
        timestamp=datetime.now(),
        priority="high"
    )
"""

from pathlib import Path
from datetime import datetime
from typing import Optional


# ============================================================================
# BASE TEMPLATE (Used by ALL watchers)
# ============================================================================

BASE_METADATA_TEMPLATE = """---
type: {type}
task_id: {task_id}
original_name: {original_name}
{additional_yaml_fields}detected: {detected}
priority: {priority}
status: pending

# AI Processing (filled by Claude Runner)
ai_processed: [PENDING]
ai_processed_at: [PENDING]
ai_category: [PENDING]
ai_decision: [PENDING]
ai_action_taken: [PENDING]
ai_response: |
  [PENDING]
---

# {title}: {original_name}

{header_fields}

---

## Content

```
{content}
```

---

## Suggested Actions

{actions}

---

## Processing Notes

<!-- CLAUDE_RESPONSE_START -->
**Category:** [PENDING]
**Decision:** [PENDING]
**Action Taken:** [PENDING]

**AI Response:**
[PENDING]
<!-- CLAUDE_RESPONSE_END -->

---

*Generated by AI Employee {watcher_name}*
*Task ID: `{task_id}`*
"""


# ============================================================================
# WATCHER-SPECIFIC FUNCTIONS
# ============================================================================

def create_file_drop_metadata(
    original_name: str,
    original_path: Path,
    content: str,
    file_hash: str,
    size: int,
    priority: str,
    timestamp: datetime,
) -> str:
    """
    Create metadata for file drop tasks (Filesystem Watcher).
    
    Uses BASE_METADATA_TEMPLATE with file_drop-specific fields.
    
    Args:
        original_name: Original filename
        original_path: Full path to original file
        content: File content
        file_hash: MD5 hash of file
        size: File size in bytes
        priority: Task priority (urgent, high, normal, low)
        timestamp: Detection timestamp
    
    Returns:
        Complete markdown content as string
    """
    task_id = f"file_drop_{timestamp.strftime('%Y%m%d_%H%M%S')}_{original_name}"
    
    # File-drop specific YAML fields
    additional_yaml_fields = f"""original_path: {original_path}
file_hash: {file_hash}
size: {_format_size(size)}
"""
    
    # File-drop specific header fields (markdown table)
    header_fields = f"""**Detected:** {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** {priority.title()}
**Size:** {_format_size(size)}
**Content Hash:** `{file_hash}`

---

## File Information

| Property | Value |
|----------|-------|
| Original Name | `{original_name}` |
| Original Path | `{original_path}` |
| Size | {_format_size(size)} |
| Detected | {timestamp.strftime('%Y-%m-%d %H:%M:%S')} |
| Content Hash | `{file_hash}` |
"""
    
    # File-drop specific actions
    actions = """- [ ] Review file contents
- [ ] Categorize and organize
- [ ] Process if needed (extract data, generate response, etc.)
- [ ] Archive after processing"""
    
    return BASE_METADATA_TEMPLATE.format(
        type="file_drop",
        task_id=task_id,
        original_name=original_name,
        additional_yaml_fields=additional_yaml_fields,
        detected=timestamp.isoformat(),
        priority=priority,
        title="File Drop",
        header_fields=header_fields,
        content=content,
        actions=actions,
        watcher_name="Filesystem Watcher"
    )


def create_email_metadata(
    from_address: str,
    subject: str,
    content: str,
    timestamp: datetime,
    priority: str = "normal",
) -> str:
    """
    Create metadata for email tasks (Gmail Watcher).
    
    Uses BASE_METADATA_TEMPLATE with email-specific fields.
    
    Args:
        from_address: Sender email address
        subject: Email subject
        content: Email body
        timestamp: Received timestamp
        priority: Task priority (urgent, high, normal, low)
    
    Returns:
        Complete markdown content as string
    """
    task_id = f"email_{timestamp.strftime('%Y%m%d_%H%M%S')}_{subject[:50]}"
    
    # Email specific YAML fields
    additional_yaml_fields = f"""from: {from_address}
subject: {subject}
received: {timestamp.isoformat()}
"""
    
    # Email specific header fields
    header_fields = f"""**From:** {from_address}
**Received:** {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** {priority.title()}
**Subject:** {subject}
"""
    
    # Email specific actions
    actions = """- [ ] Reply to sender
- [ ] Forward to relevant party
- [ ] Archive after processing"""
    
    return BASE_METADATA_TEMPLATE.format(
        type="email",
        task_id=task_id,
        original_name=subject,
        additional_yaml_fields=additional_yaml_fields,
        detected=timestamp.isoformat(),
        priority=priority,
        title="Email",
        header_fields=header_fields,
        content=content,
        actions=actions,
        watcher_name="Gmail Watcher"
    )


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def _format_size(size: int) -> str:
    """Format file size in human-readable format."""
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size < 1024:
            return f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"


# ============================================================================
# TEMPLATE FILLING FUNCTIONS (For Claude Runner)
# ============================================================================

import re
from datetime import datetime
from typing import Dict, Any


def fill_ai_placeholders(content: str, decision: Dict[str, Any]) -> str:
    """
    Fill all AI-related placeholders in metadata file with Claude's response.
    
    Args:
        content: Original markdown content with [PENDING] placeholders
        decision: Claude's JSON response (decision, category, ai_action_taken, ai_response)
    
    Returns:
        Updated content with all placeholders filled
    """
    timestamp = datetime.now().isoformat()
    
    # Fill YAML frontmatter placeholders
    content = re.sub(
        r'ai_processed: \[PENDING\]',
        f'ai_processed: true',
        content
    )
    content = re.sub(
        r'ai_processed_at: \[PENDING\]',
        f'ai_processed_at: {timestamp}',
        content
    )
    content = re.sub(
        r'ai_category: \[PENDING\]',
        f'ai_category: {decision.get("category", "unknown")}',
        content
    )
    content = re.sub(
        r'ai_decision: \[PENDING\]',
        f'ai_decision: {decision.get("decision", "unknown")}',
        content
    )
    content = re.sub(
        r'ai_action_taken: \[PENDING\]',
        f'ai_action_taken: {decision.get("ai_action_taken", "unknown")}',
        content
    )
    
    # Fill ai_response in YAML (handle multi-line)
    ai_response = decision.get("ai_response", "No response")
    # Escape pipe characters and indent properly
    escaped_response = ai_response.replace('|', '\\|')
    # Match the exact pattern with proper escaping
    content = re.sub(
        r'ai_response: \|\n  \[PENDING\]',
        f'ai_response: |\n  {escaped_response}',
        content
    )
    
    # Fill body placeholders (Processing Notes section)
    category = decision.get("category", "unknown").title()
    action_taken = decision.get("ai_action_taken", "unknown")
    
    body_replacement = f"""<!-- CLAUDE_RESPONSE_START -->
**Category:** {category}
**Decision:** {decision.get("decision", "unknown")}
**Action Taken:** {action_taken}

**AI Response:**
{ai_response}
<!-- CLAUDE_RESPONSE_END -->"""
    
    # Find and replace the entire CLAUDE_RESPONSE section
    pattern = r'<!-- CLAUDE_RESPONSE_START -->.*?<!-- CLAUDE_RESPONSE_END -->'
    content = re.sub(pattern, body_replacement, content, flags=re.DOTALL)
    
    return content


def validate_no_pending_placeholders(content: str) -> bool:
    """
    Validate that all [PENDING] placeholders have been replaced.
    
    Args:
        content: Markdown content to validate
    
    Returns:
        True if no [PENDING] found, False otherwise
    """
    return '[PENDING]' not in content


def get_pending_count(content: str) -> int:
    """
    Count remaining [PENDING] placeholders.
    
    Args:
        content: Markdown content
    
    Returns:
        Number of remaining [PENDING] placeholders
    """
    return content.count('[PENDING]')
