# task_template.py - INPUT-ONLY templates for Option B (Claude owns the vault)
# Claude reads these files directly via file tools.
# No JSON output. No build_output_file. No Processing_Archive.

from pathlib import Path
from datetime import datetime
from typing import Tuple


# ============================================================================
# INTERNAL UTILITIES (minimal)
# ============================================================================

def _format_size(size: int) -> str:
    """Format file size as human-readable string."""
    for unit in ["B", "KB", "MB", "GB"]:
        if size < 1024:
            return f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"


def _make_safe_stem(name: str, max_len: int = 40) -> str:
    """Convert name into safe task ID stem."""
    stem = Path(name).stem
    safe = "".join(c if c.isalnum() or c in "._-" else "_" for c in stem)
    return safe[:max_len]


def _truncate_content(content: str, max_length: int = 4000) -> str:
    """Truncate content (Claude context is large but we stay safe)."""
    if len(content) <= max_length:
        return content
    truncated = content[: max_length - 250]
    omitted = len(content) - max_length + 250
    return (
        truncated
        + f"\n\n---\n\n[Content truncated — {omitted} characters omitted. "
        f"Full original is available in Gmail.]\n"
    )


# ============================================================================
# TASK FILE CREATION (Watcher calls these — keep exactly as you use them)
# ============================================================================

def create_email_task_enhanced(
    from_address: str,
    to_address: str,
    subject: str,
    content: str,
    timestamp: datetime,
    priority: str = "normal",
    filter_reason: str = "",
    is_reply: bool = False,
    gmail_message_id: str = "",
    gmail_link: str = "",
) -> Tuple[str, str]:
    """
    Clean INPUT-ONLY template for Option B (Claude + Ralph Wiggum).
    No instructions. No JSON. No AI status fields.
    """
    timestamp_str = timestamp.strftime("%Y%m%d_%H%M%S")
    safe_stem = _make_safe_stem(subject)
    task_id = f"email_{timestamp_str}_{safe_stem}"

    gmail_msgid_hex = format(int(gmail_message_id), "x") if gmail_message_id else ""
    gmail_url = (
        f"https://mail.google.com/mail/u/0/#inbox/{gmail_msgid_hex}"
        if gmail_msgid_hex
        else gmail_link
    )

    thread_text = "Yes (reply in thread)" if is_reply else "No (new email)"

    task_content = f"""---
type: email
task_id: {task_id}
from: "{from_address}"
to: "{to_address}"
subject: "{subject}"
received: {timestamp.isoformat()}
priority: {priority}
status: pending
filter_reason: {filter_reason}
is_reply: {str(is_reply).lower()}
gmail_message_id: {gmail_message_id}
---

# Email: {subject}

## Quick Actions (Human)
📧 **[Open in Gmail]({gmail_url})**  
📋 **Task ID:** `{task_id}`  
🧵 **Thread:** {thread_text}

---

## Email Information

| Property      | Value                          |
|---------------|--------------------------------|
| From          | {from_address}                 |
| To            | {to_address}                   |
| Received      | {timestamp.strftime('%Y-%m-%d %H:%M:%S')} |
| Priority      | {priority.title()}             |
| Filter Reason | {filter_reason or "None"}      |

---

## Body

{content}

---

*Generated by AI Employee Gmail Watcher • Task ID: `{task_id}`*
"""

    return task_id, task_content

# Keep these if you still use them (file drops + WhatsApp)
def create_file_drop_task(
    original_name: str,
    original_path: Path,
    content: str,
    content_type: str,
    file_extension: str,
    file_hash: str,
    size_bytes: int,
    priority: str,
    timestamp: datetime,
) -> Tuple[str, str]:
    timestamp_str = timestamp.strftime("%Y%m%d_%H%M%S")
    safe_stem = _make_safe_stem(original_name)
    task_id = f"file_drop_{timestamp_str}_{safe_stem}"

    size_formatted = _format_size(size_bytes)

    if content_type == "binary" or not content:
        content_section = "_Binary file — content not extractable. Claude will decide based on filename and extension only._"
    else:
        content_section = f"```\n{_truncate_content(content)}\n```"

    task_content = f"""---
type: file_drop
task_id: {task_id}
original_name: {original_name}
file_extension: {file_extension}
content_type: {content_type}
file_hash: {file_hash}
size: {size_formatted}
detected: {timestamp.isoformat()}
priority: {priority}
status: pending
---

# File Drop: {original_name}

**Detected:** {timestamp.strftime('%Y-%m-%d %H:%M:%S')}  
**Size:** {size_formatted}  
**Priority:** {priority.title()}  
**Extension:** {file_extension}

---

## File content

{content_section}

---

*Generated by AI Employee Filesystem Watcher • Task ID: `{task_id}`*
"""

    return task_id, task_content

