"""
task_template.py - Centralized metadata file templates

All watchers use the same base template with different field values.
This ensures consistency across all task types (file_drop, email, whatsapp, etc.)

Usage:
    from utils.task_template import create_file_drop_metadata, create_email_metadata
    
    # For Filesystem Watcher
    metadata = create_file_drop_metadata(
        original_name="invoice.pdf",
        original_path=Path("vault/Inbox/Drop/invoice.pdf"),
        content="File content...",
        file_hash="abc123...",
        size=1024,
        priority="high",
        timestamp=datetime.now()
    )
    
    # For Gmail Watcher (future)
    metadata = create_email_metadata(
        from_address="client@example.com",
        subject="Invoice #123",
        content="Email body...",
        timestamp=datetime.now(),
        priority="high"
    )
"""

from pathlib import Path
from datetime import datetime
from typing import Optional


# ============================================================================
# BASE TEMPLATE (Used by ALL watchers)
# ============================================================================

BASE_METADATA_TEMPLATE = """---
type: {type}
task_id: {task_id}
original_name: {original_name}
{additional_yaml_fields}detected: {detected}
priority: {priority}
status: pending
---

# {title}: {original_name}

{header_fields}

---

## Content

```
{content}
```

---

## Suggested Actions

{actions}

---

## Processing Notes

(Add notes here during processing)

---

*Generated by AI Employee {watcher_name}*
*Task ID: `{task_id}`*
"""


# ============================================================================
# WATCHER-SPECIFIC FUNCTIONS
# ============================================================================

def create_file_drop_metadata(
    original_name: str,
    original_path: Path,
    content: str,
    file_hash: str,
    size: int,
    priority: str,
    timestamp: datetime,
) -> str:
    """
    Create metadata for file drop tasks (Filesystem Watcher).
    
    Uses BASE_METADATA_TEMPLATE with file_drop-specific fields.
    
    Args:
        original_name: Original filename
        original_path: Full path to original file
        content: File content
        file_hash: MD5 hash of file
        size: File size in bytes
        priority: Task priority (urgent, high, normal, low)
        timestamp: Detection timestamp
    
    Returns:
        Complete markdown content as string
    """
    task_id = f"file_drop_{timestamp.strftime('%Y%m%d_%H%M%S')}_{original_name}"
    
    # File-drop specific YAML fields
    additional_yaml_fields = f"""original_path: {original_path}
file_hash: {file_hash}
size: {_format_size(size)}
"""
    
    # File-drop specific header fields (markdown table)
    header_fields = f"""**Detected:** {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** {priority.title()}
**Size:** {_format_size(size)}
**Content Hash:** `{file_hash}`

---

## File Information

| Property | Value |
|----------|-------|
| Original Name | `{original_name}` |
| Original Path | `{original_path}` |
| Size | {_format_size(size)} |
| Detected | {timestamp.strftime('%Y-%m-%d %H:%M:%S')} |
| Content Hash | `{file_hash}` |
"""
    
    # File-drop specific actions
    actions = """- [ ] Review file contents
- [ ] Categorize and organize
- [ ] Process if needed (extract data, generate response, etc.)
- [ ] Archive after processing"""
    
    return BASE_METADATA_TEMPLATE.format(
        type="file_drop",
        task_id=task_id,
        original_name=original_name,
        additional_yaml_fields=additional_yaml_fields,
        detected=timestamp.isoformat(),
        priority=priority,
        title="File Drop",
        header_fields=header_fields,
        content=content,
        actions=actions,
        watcher_name="Filesystem Watcher"
    )


def create_email_metadata(
    from_address: str,
    subject: str,
    content: str,
    timestamp: datetime,
    priority: str = "normal",
) -> str:
    """
    Create metadata for email tasks (Gmail Watcher).
    
    Uses BASE_METADATA_TEMPLATE with email-specific fields.
    
    Args:
        from_address: Sender email address
        subject: Email subject
        content: Email body
        timestamp: Received timestamp
        priority: Task priority (urgent, high, normal, low)
    
    Returns:
        Complete markdown content as string
    """
    task_id = f"email_{timestamp.strftime('%Y%m%d_%H%M%S')}_{subject[:50]}"
    
    # Email specific YAML fields
    additional_yaml_fields = f"""from: {from_address}
subject: {subject}
received: {timestamp.isoformat()}
"""
    
    # Email specific header fields
    header_fields = f"""**From:** {from_address}
**Received:** {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** {priority.title()}
**Subject:** {subject}
"""
    
    # Email specific actions
    actions = """- [ ] Reply to sender
- [ ] Forward to relevant party
- [ ] Archive after processing"""
    
    return BASE_METADATA_TEMPLATE.format(
        type="email",
        task_id=task_id,
        original_name=subject,
        additional_yaml_fields=additional_yaml_fields,
        detected=timestamp.isoformat(),
        priority=priority,
        title="Email",
        header_fields=header_fields,
        content=content,
        actions=actions,
        watcher_name="Gmail Watcher"
    )


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def _format_size(size: int) -> str:
    """Format file size in human-readable format."""
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size < 1024:
            return f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"
